### PR TITLE
Changed Statusbrush to ImageBrush. Updated csproj to copy Icons

### PR DESCRIPTION
**Pull request by TimBo93**
screenshot

The status icons can be modified in the ressources folder.
They will be copied automatically to output build directory.

### CODE REVIEW

**Comment by Impyy** [comment]
Why did you decide to make these images actual files in the directory of Toxy instead of just embedded resources? Seems kind of inconvenient to me.

**Comment by TimBo93** [comment]
You can edit the icons without compiling. I thought for dev time its could be okay. In my opinion images shouldn't be a part of a dll. The compiletime is bigger and every change of the Images need a build. But i can change this if you want to. =)

**Comment by Impyy** [comment]
I'd prefer having them as embedded resources for the sake of consistency for now. I like what you did to the 'busy indicator' though, the offline and busy indicators looked way too similar ;)

**Comment by TimBo93** [comment]
now it would be into binary

**Pull request merged**
